stages:
  - setup
  - sections
  - calendars
  - certificates
  - courses
  - students

setup:
  stage: setup
  image: python:3.10
  script:
    - set -e  # Enable exit on non-zero status
    - echo "Installing dependencies..."
    - apt-get update && apt-get install -y gcc wget
    - wget https://dlm.mariadb.com/2678574/Connectors/c/connector-c-3.3.3/mariadb-connector-c-3.3.3-debian-bullseye-amd64.tar.gz -O - | tar -zxf - --strip-components=1 -C /usr
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install mariadb==1.1.6
    - pip3 install --upgrade mariadb
    - pip3 install email-validator

    - echo $DB_NAME
    - echo $DB_HOST
    - echo $DB_USER
    - echo $DB_PASSWORD
    - echo $DB_PORT
    - echo $SECRET_KEY
    - echo $ACCESS_TOKEN_EXPIRES_MINUTES
    - echo $ALGORITHM
    - echo $API_KEY
    - echo $API_SECRET
    - echo $VIDEO_API_KEY

sections_test:
  stage: sections
  image: python:3.10
  script:
    - cd app/
    - python3 -m unittest tests/sections_services_test.py


calendars_test:
  stage: calendars
  image: python:3.10
  script:
    - cd app/
    - python3 -m unittest tests/calendars_services_test.py

certificates_test:
  stage: certificates
  image: python:3.10
  script:
    - cd app/
    - python3 -m unittest tests/certificates_service_test.py

courses_test:
  stage: courses
  image: python:3.10
  script:
    - cd app/
    - python3 -m unittest tests/courses_service_test.py

students_test:
  stage: students
  image: python:3.10
  script:
    - cd app/
    - python3 -m unittest tests/students_services_test.py
