variables:
  IMAGE_NAME: ampersandio/poodlebox
  IMAGE_TAG: python-app-1.0

# stages:
#   - test

build_image:
  image: docker:24.0
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    # - set -e  # Enable exit on non-zero status
    # - echo "Installing dependencies..."
    # - apt-get update && apt-get install -y gcc wget
    # - wget https://dlm.mariadb.com/2678574/Connectors/c/connector-c-3.3.3/mariadb-connector-c-3.3.3-debian-bullseye-amd64.tar.gz -O - | tar -zxf - --strip-components=1 -C /usr
    # - pip3 install --upgrade pip
    # - pip3 install -r requirements.txt
    # - pip3 install mariadb==1.1.6
    # - pip3 install --upgrade mariadb
    # - pip3 install email-validator
    # - cd app/
    # - echo $DB_NAME
    # - echo $DB_HOST
    # - echo $DB_USER
    # - echo $DB_PASSWORD
    # - echo $DB_PORT
    # - echo $SECRET_KEY
    # - echo $ACCESS_TOKEN_EXPIRES_MINUTES
    # - echo $ALGORITHM
    # - echo $API_KEY
    # - echo $API_SECRET
    # - echo $VIDEO_API_KEY

    # - python3 -m unittest tests/sections_services_test.py
    # - python3 -m unittest tests/calendars_services_test.py
    # - python3 -m unittest tests/certificates_service_test.py
    # - python3 -m unittest tests/courses_service_test.py
    # - python3 -m unittest tests/students_services_test.py
