stages:
  - test

test:
  stage: test
  image: python:3.10
  script:
    - echo "Installing dependencies..."

    - apt-get update && apt-get install -y gcc wget
    - wget https://dlm.mariadb.com/2678574/Connectors/c/connector-c-3.3.3/mariadb-connector-c-3.3.3-debian-bullseye-amd64.tar.gz -O - | tar -zxf - --strip-components=1 -C /usr
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install mariadb==1.1.6
    - pip3 install --upgrade mariadb
    - cd app/
    - python3 -m unittest tests/sections_services_test.py